
### 상품 등록
POST http://localhost:8081/seller/product
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhWlM2amFldldFcjNrcWkybHV4VGpxSFN3eDdOT21YTUtrREp0T2VGZU8wPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc1MjY0ODI3LCJleHAiOjE2NzUzNTEyMjd9.UGEzWE4N9pma2wq88ut_bRIwnTrC54FOlu7FIK9FC8c
Content-Type: application/json

{
  "description": "컴퓨터.",
  "items": [
    {
      "count": 1,
      "name": "컴퓨터 1",
      "price": 10
    }
  ],
  "name": "컴퓨터"
}

### 아이템 추가 등록
POST http://localhost:8081/seller/product/item
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhWlM2amFldldFcjNrcWkybHV4VGpxSFN3eDdOT21YTUtrREp0T2VGZU8wPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc1MjY0ODI3LCJleHAiOjE2NzUzNTEyMjd9.UGEzWE4N9pma2wq88ut_bRIwnTrC54FOlu7FIK9FC8c
Content-Type: application/json

{
  "productId": 10,
  "count": 3,
  "name": "코카콜라",
  "price": 1000
}

<> 2022-04-20T232308.200.json

### 상품 수정 ( 판매자 )
PUT http://localhost:8081/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhWlM2amFldldFcjNrcWkybHV4VGpxSFN3eDdOT21YTUtrREp0T2VGZU8wPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc1MjY0ODI3LCJleHAiOjE2NzUzNTEyMjd9.UGEzWE4N9pma2wq88ut_bRIwnTrC54FOlu7FIK9FC8c

{
  "description": "컴퓨터",
  "items": [
    {
      "id": 28,
      "name": "컴퓨터1",
      "price": 20000,
      "count": 8
    }
  ],
  "id": 10,
  "name" : "컴퓨터1"
}

### 아이템 수정 ( 판매자 )
PUT http://localhost:8081/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhWlM2amFldldFcjNrcWkybHV4VGpxSFN3eDdOT21YTUtrREp0T2VGZU8wPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc1MjY0ODI3LCJleHAiOjE2NzUzNTEyMjd9.UGEzWE4N9pma2wq88ut_bRIwnTrC54FOlu7FIK9FC8c

{
  "id" : 28,
  "name": "펩시",
  "price": 20000,
  "count": 10
}

### 상품 삭제 ( 셀러 )
DELETE http://localhost:8081/seller/product?id=1
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhWlM2amFldldFcjNrcWkybHV4VGpxSFN3eDdOT21YTUtrREp0T2VGZU8wPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc1MjY0ODI3LCJleHAiOjE2NzUzNTEyMjd9.UGEzWE4N9pma2wq88ut_bRIwnTrC54FOlu7FIK9FC8c

### 아이템 삭제 ( 셀러 )
DELETE http://localhost:8081/seller/product/item?id=1
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhWlM2amFldldFcjNrcWkybHV4VGpxSFN3eDdOT21YTUtrREp0T2VGZU8wPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc1MjY0ODI3LCJleHAiOjE2NzUzNTEyMjd9.UGEzWE4N9pma2wq88ut_bRIwnTrC54FOlu7FIK9FC8c

### 상품 검색
GET http://localhost:8081/search/product?name=상품
Content-Type: application/json

<> 2022-04-20T232449.200.json

### 상품 디테일
GET http://localhost:8081/search/product/detail?productId=1
Content-Type: application/json


### (고객) 상품 확인
GET http://localhost:8081/customer/cart
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRQ0lrZkJUZFJXazhoNEhIMFFNZU1nZzhUNTV1aTVkSlZxcFgwK29OVkNJPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NTA0NjI0OTksImV4cCI6MTY1MDQ2NjA5OX0.eW-VShvsTSw0k7fRd95BHkTZiUON5l48kICeHIyZ2Fg
Content-Type: application/json


### (고객) 카트에 담기 (실패)
PUT http://localhost:8081/customer/cart
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRQ0lrZkJUZFJXazhoNEhIMFFNZU1nZzhUNTV1aTVkSlZxcFgwK29OVkNJPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NTA0NjI0OTksImV4cCI6MTY1MDQ2NjA5OX0.eW-VShvsTSw0k7fRd95BHkTZiUON5l48kICeHIyZ2Fg
Content-Type: application/json

{
  "description": "상품입니다",
  "items": [
    {
      "count": 100,
      "id": 1,
      "name": "아이템 1",
      "price": 100
    }
  ],
  "name": "상품명",
  "productId": 1,
  "sellerId": 1
}

### (고객) 카트에 담기 (성공)
PUT http://localhost:8081/customer/cart
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRQ0lrZkJUZFJXazhoNEhIMFFNZU1nZzhUNTV1aTVkSlZxcFgwK29OVkNJPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NTA0NjI0OTksImV4cCI6MTY1MDQ2NjA5OX0.eW-VShvsTSw0k7fRd95BHkTZiUON5l48kICeHIyZ2Fg
Content-Type: application/json

{
  "description": "상품입니다",
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "아이템 1",
      "price": 10
    }
  ],
  "name": "상품명",
  "productId": 1,
  "sellerId": 1
}

### (고객) 주문
POST http://localhost:8081/customer/order
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRQ0lrZkJUZFJXazhoNEhIMFFNZU1nZzhUNTV1aTVkSlZxcFgwK29OVkNJPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NTA0NjY4MTUsImV4cCI6MTY1MDQ3MDQxNX0.FKvJoVYxu8rLFfF5Y5eZHbm0dDbesNkKeVdCAX9UkW4
Content-Type: application/json

{
  "products": [
    {
      "items": [
        {
          "count": 1,
          "id": 1,
          "name": "아이템 1",
          "price": 10
        }
      ],
      "name": "상품명",
      "productId": 1,
      "sellerId": 1
    }
  ]
}

<> 2022-04-21T000350.400.json
<> 2022-04-21T000233.400.json
<> 2022-04-21T000112.500.json
<> 2022-04-21T000027.500.json
<> 2022-04-20T235946.500.json
<> 2022-04-20T235931.405.json
